/*
 * This file was generated by AI and is not subject to copyright protection.
 * AI-generated content is not applicable for copyright.
 */
package com.github.ananbox

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.PorterDuff
import android.graphics.SurfaceTexture
import android.os.SystemClock
import android.util.AttributeSet
import android.util.Log
import android.util.SparseArray
import android.view.TextureView
import android.view.View
import java.io.BufferedReader
import java.io.File
import java.io.InputStreamReader
import java.io.InterruptedIOException
import java.util.LinkedList
import java.util.concurrent.atomic.AtomicBoolean
import kotlin.concurrent.thread

/**
 * A TextureView that displays boot logs with color coding similar to twoyi.
 * 
 * Inspired by twoyi's BootLogTexture implementation.
 */
class BootLogView @JvmOverloads constructor(
    context: Context,
    attrs: AttributeSet? = null,
    defStyleAttr: Int = 0
) : TextureView(context, attrs, defStyleAttr), TextureView.SurfaceTextureListener {

    companion object {
        private const val TAG = "BootLogView"
        private const val MAX_LINES = 160
        private const val MAX_LINES_PER_ITERATION = 50  // Limit lines read per iteration
        
        // Color map for different log levels (based on twoyi)
        private val COLOR_MAP = mapOf(
            'V' to 0xBBBBBB,
            'D' to 0x5EBB1E,
            'I' to 0x4CBBA2,
            'W' to 0xFFD21C,
            'E' to 0xFF6B68,
            'F' to Color.RED,
            'S' to Color.WHITE
        )
    }

    private val rendering = AtomicBoolean(false)
    private val logMessages = LimitedQueue<String>(MAX_LINES)
    private val snapshot = LinkedList<String>()
    private val paints = SparseArray<Paint>()
    private val defaultPaint = Paint()
    private var logcatProcess: Process? = null
    private var logcatThread: Thread? = null
    private val hasNewContent = AtomicBoolean(false)

    init {
        surfaceTextureListener = this
        
        // Initialize paints for each log level
        COLOR_MAP.forEach { (key, color) ->
            val paint = Paint().apply {
                this.color = color
                isAntiAlias = true
                textSize = 16f
                alpha = 192  // Slightly more opaque than twoyi for better readability
            }
            paints.put(key.code, paint)
        }
        
        // Default paint for unrecognized log levels
        defaultPaint.apply {
            color = Color.WHITE
            isAntiAlias = true
            textSize = 16f
            alpha = 192
        }
    }

    override fun onAttachedToWindow() {
        super.onAttachedToWindow()
        rendering.set(true)
    }

    override fun onDetachedFromWindow() {
        super.onDetachedFromWindow()
        rendering.set(false)
        stopLogcat()
    }

    override fun onVisibilityChanged(changedView: View, visibility: Int) {
        super.onVisibilityChanged(changedView, visibility)
        rendering.set(visibility == VISIBLE)
        
        if (visibility != VISIBLE) {
            stopLogcat()
        }
    }

    override fun onSurfaceTextureAvailable(surface: SurfaceTexture, width: Int, height: Int) {
        // Start logcat capture
        startLogcat()
        
        // Start rendering loop with adaptive frame rate
        thread(name = "BootLogView-Renderer") {
            var idleFrames = 0
            while (rendering.get()) {
                if (hasNewContent.getAndSet(false)) {
                    // New content available - render at full speed
                    render()
                    idleFrames = 0
                    SystemClock.sleep(16) // ~60 FPS
                } else {
                    // No new content - reduce frame rate to save CPU
                    idleFrames++
                    if (idleFrames < 30) {
                        // First 0.5 second: still render at 60 FPS
                        render()
                        SystemClock.sleep(16)
                    } else {
                        // After 0.5 second: reduce to 10 FPS
                        render()
                        SystemClock.sleep(100)
                    }
                }
            }
        }
    }

    override fun onSurfaceTextureSizeChanged(surface: SurfaceTexture, width: Int, height: Int) {
        // Nothing to do
    }

    override fun onSurfaceTextureDestroyed(surface: SurfaceTexture): Boolean {
        rendering.set(false)
        stopLogcat()
        return true
    }

    override fun onSurfaceTextureUpdated(surface: SurfaceTexture) {
        // Nothing to do
    }

    private fun startLogcat() {
        stopLogcat()  // Ensure no previous process is running
        
        logcatThread = thread(name = "BootLogView-Logcat") {
            try {
                // Read from container.logcat file if it exists, otherwise use logcat
                val containerLogFile = File(context.filesDir, "container.logcat")
                
                if (containerLogFile.exists()) {
                    // Read from container logcat file
                    Log.d(TAG, "Reading logs from container.logcat")
                    readFromFile(containerLogFile)
                } else {
                    // Fallback to system logcat
                    Log.d(TAG, "Reading logs from system logcat")
                    readFromLogcat()
                }
            } catch (e: Exception) {
                Log.e(TAG, "Error reading logs", e)
            }
        }
    }

    private fun readFromFile(file: File) {
        var randomAccessFile: java.io.RandomAccessFile? = null
        try {
            // Use RandomAccessFile for efficient tailing
            randomAccessFile = java.io.RandomAccessFile(file, "r")
            var lastPosition = 0L  // Start at beginning to show existing boot logs
            
            while (rendering.get()) {
                val currentSize = file.length()
                
                if (currentSize < lastPosition) {
                    // File was truncated, restart from beginning
                    lastPosition = 0
                    randomAccessFile.seek(0)
                } else if (currentSize > lastPosition) {
                    // New content available - read up to MAX_LINES_PER_ITERATION lines per iteration
                    randomAccessFile.seek(lastPosition)
                    
                    var linesRead = 0
                    var line = randomAccessFile.readLine()
                    while (line != null && linesRead < MAX_LINES_PER_ITERATION && randomAccessFile.filePointer <= currentSize) {
                        addLogLine(line)
                        lastPosition = randomAccessFile.filePointer
                        line = randomAccessFile.readLine()
                        linesRead++
                    }
                } else {
                    // No new data, wait a bit
                    SystemClock.sleep(100)
                }
            }
        } catch (e: InterruptedIOException) {
            Log.d(TAG, "File reading interrupted (shutdown)")
        } catch (e: Exception) {
            Log.e(TAG, "Error reading from file", e)
        } finally {
            try {
                randomAccessFile?.close()
            } catch (e: Exception) {
                Log.e(TAG, "Error closing RandomAccessFile", e)
            }
        }
    }

    private fun readFromLogcat() {
        var reader: BufferedReader? = null
        try {
            // Show all logs from boot (no -T parameter to capture boot sequence)
            logcatProcess = Runtime.getRuntime().exec(arrayOf(
                "logcat",
                "-v", "brief",  // Brief format like twoyi
                "*:I"  // Info level and above
            ))
            
            reader = BufferedReader(InputStreamReader(logcatProcess!!.inputStream))
            
            while (rendering.get()) {
                val line = reader.readLine() ?: break
                addLogLine(line)
            }
        } catch (e: InterruptedIOException) {
            Log.d(TAG, "Logcat reading interrupted (shutdown)")
        } catch (e: Exception) {
            Log.e(TAG, "Error reading from logcat", e)
        } finally {
            try {
                reader?.close()
            } catch (e: Exception) {
                Log.e(TAG, "Error closing BufferedReader", e)
            }
        }
    }

    private fun addLogLine(line: String) {
        if (line.isEmpty()) return
        
        logMessages.add(line)  // Now thread-safe with synchronized add()
        hasNewContent.set(true)  // Signal that new content is available
    }

    private fun stopLogcat() {
        logcatProcess?.destroy()
        logcatProcess = null
        logcatThread?.interrupt()
        logcatThread = null
    }

    private fun render() {
        var canvas: Canvas? = null
        try {
            canvas = lockCanvas() ?: return
            
            // Clear canvas
            canvas.drawColor(Color.TRANSPARENT, PorterDuff.Mode.CLEAR)
            
            snapshot.clear()
            snapshot.addAll(logMessages.snapshot())  // Use thread-safe snapshot method
            
            var yPosition = 20f
            for (log in snapshot) {
                if (yPosition > height) break
                
                // Extract log level from logcat format (e.g., "I/TAG: message" or "I( 1234): message")
                val logLevel = extractLogLevel(log)
                val paint = paints.get(logLevel.code) ?: defaultPaint
                
                canvas.drawText(log, 8f, yPosition, paint)
                yPosition += 20f
            }
        } catch (e: Exception) {
            Log.e(TAG, "Error rendering", e)
        } finally {
            canvas?.let { unlockCanvasAndPost(it) }
        }
    }
    
    /**
     * Extract log level character from log line.
     * Handles various log formats:
     * - "I/TAG: message" -> 'I'
     * - "I( 1234): message" -> 'I'
     * - "INFO message" -> 'I'
     * - Default to first character if no pattern matches
     */
    private fun extractLogLevel(log: String): Char {
        if (log.isEmpty()) return ' '
        
        // Check for standard Android logcat format: "I/" or "I("
        if (log.length >= 2 && (log[1] == '/' || log[1] == '(')) {
            return log[0]
        }
        
        // Check for long format log level names
        when {
            log.startsWith("VERBOSE", ignoreCase = true) -> return 'V'
            log.startsWith("DEBUG", ignoreCase = true) -> return 'D'
            log.startsWith("INFO", ignoreCase = true) -> return 'I'
            log.startsWith("WARN", ignoreCase = true) -> return 'W'
            log.startsWith("ERROR", ignoreCase = true) -> return 'E'
            log.startsWith("FATAL", ignoreCase = true) -> return 'F'
        }
        
        // Default to first character
        return log[0]
    }
    
    /**
     * Stop rendering and cleanup resources
     */
    fun stop() {
        rendering.set(false)
        stopLogcat()
    }
}
