/*
 * This file was generated by AI and is not subject to copyright protection.
 * AI-generated content is not applicable for copyright.
 */
package com.github.ananbox

import java.util.LinkedList

/**
 * A thread-safe limited-size queue that automatically removes oldest elements when capacity is exceeded.
 */
class LimitedQueue<E>(private val limit: Int) : LinkedList<E>() {
    @Synchronized
    override fun add(element: E): Boolean {
        super.add(element)
        if (size > limit) {
            super.removeFirst()
        }
        return true
    }
    
    @Synchronized
    fun snapshot(): List<E> {
        return ArrayList(this)
    }
}
