/*
 * This file was generated by AI and is not subject to copyright protection.
 * It is dedicated to the public domain.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranties of
 * MERCHANTABILITY, SATISFACTORY QUALITY, or FITNESS FOR A PARTICULAR
 * PURPOSE.
 */

#ifndef ANBOX_SERVER_ADB_FORWARDER_H_
#define ANBOX_SERVER_ADB_FORWARDER_H_

#include "anbox/runtime.h"
#include "anbox/network/tcp_socket_connector.h"
#include "anbox/network/connections.h"
#include "anbox/network/socket_connection.h"

#include <memory>
#include <mutex>
#include <atomic>
#include <string>
#include <thread>
#include <vector>

namespace anbox::server {

/**
 * ADB Forwarder - forwards connections from a TCP port to the Android container's
 * ADB socket (/dev/socket/adbd).
 * 
 * This allows external ADB clients to connect to the container and enables
 * tools like scrcpy to work with the containerized Android.
 */
class AdbForwarder {
public:
    /**
     * Create an ADB forwarder.
     * @param runtime The async I/O runtime
     * @param listen_address The address to listen on (e.g., "0.0.0.0")
     * @param listen_port The port to listen on (e.g., 5555)
     * @param adb_socket_path Path to the ADB socket inside rootfs (e.g., "/dev/socket/adbd")
     * @param rootfs_path Path to the rootfs directory
     */
    AdbForwarder(const std::shared_ptr<Runtime>& runtime,
                 const std::string& listen_address,
                 uint16_t listen_port,
                 const std::string& adb_socket_path,
                 const std::string& rootfs_path);
    ~AdbForwarder();

    // Start the forwarder
    void start();

    // Stop the forwarder
    void stop();

    // Check if any client is connected
    bool has_clients() const;

    // Get listen address
    std::string listen_address() const { return listen_address_; }
    
    // Get listen port
    uint16_t listen_port() const { return listen_port_; }

private:
    void on_new_connection(std::shared_ptr<boost::asio::ip::tcp::socket> const& socket);
    void forward_data(int client_fd, int adb_fd, int connection_id);
    int connect_to_adb_socket();

    std::shared_ptr<Runtime> runtime_;
    std::string listen_address_;
    uint16_t listen_port_;
    std::string adb_socket_path_;
    std::string rootfs_path_;
    std::shared_ptr<network::TcpSocketConnector> connector_;
    
    std::atomic<int> next_id_{0};
    std::atomic<bool> running_{false};
    std::atomic<int> client_count_{0};
    
    // Threads for forwarding data
    std::vector<std::thread> forward_threads_;
    mutable std::mutex mutex_;
};

} // namespace anbox::server

#endif // ANBOX_SERVER_ADB_FORWARDER_H_
