/*
 * This file was generated by AI and is not subject to copyright protection.
 * It is dedicated to the public domain.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranties of
 * MERCHANTABILITY, SATISFACTORY QUALITY, or FITNESS FOR A PARTICULAR
 * PURPOSE.
 */

#ifndef ANBOX_SERVER_STREAMING_LAYER_COMPOSER_H_
#define ANBOX_SERVER_STREAMING_LAYER_COMPOSER_H_

#include "anbox/graphics/layer_composer.h"
#include "anbox/graphics/emugl/Renderable.h"
#include "anbox/graphics/emugl/Renderer.h"

#include <memory>
#include <functional>
#include <vector>

namespace anbox::server {

/**
 * A LayerComposer that captures rendered frames and streams them to clients
 * instead of displaying them on a native window.
 */
class StreamingLayerComposer : public graphics::LayerComposer {
public:
    using FrameCallback = std::function<void(const void* data, uint32_t width, 
                                              uint32_t height, uint32_t stride)>;

    StreamingLayerComposer(const std::shared_ptr<::Renderer>& renderer,
                           const std::shared_ptr<graphics::Rect>& rect);
    ~StreamingLayerComposer() override;

    // Set the callback to receive rendered frames
    void set_frame_callback(FrameCallback callback);
    
    // Override submit_layers to capture frames instead of displaying
    void submit_layers(const RenderableList& renderables) override;

private:
    std::shared_ptr<::Renderer> renderer_;
    std::shared_ptr<graphics::Rect> rect_;
    FrameCallback frame_callback_;
    std::vector<uint8_t> pixel_buffer_;
};

} // namespace anbox::server

#endif // ANBOX_SERVER_STREAMING_LAYER_COMPOSER_H_
